version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    steps:
      - checkout
      - run: cp -r vendor/* $GOPATH/src/
      - run: go test -args --id 3135556 --username $USERNAME --password $PASSWORD
